// ============================================================
// EXAMPLES
// ============================================================
export const EXAMPLES = {
  counter: [
    "// ========================================",
    "// COUNTER",
    "// ========================================",
    "const store = createStore({ count: 0 });",
    "",
    "store.select((s) => s.count, (count) => {",
    "  console.log('Count:', count);",
    "});",
    "",
    "store.setKey('count', 1);",
    "store.setKey('count', (n) => n + 1);",
    "store.setKey('count', (n) => n + 1);",
    "store.setKey('count', (n) => n - 1);",
  ].join("\n"),

  todo: [
    "// ========================================",
    "// TODO LIST",
    "// ========================================",
    "const todos = createStore({",
    "  items: [],",
    "  filter: 'all',",
    "});",
    "",
    "todos.on('add', (e) => {",
    "  todos.setKey('items', (items) => [",
    "    ...items,",
    "    { id: Date.now(), text: e.data.text, done: false },",
    "  ]);",
    "});",
    "",
    "todos.on('toggle', (e) => {",
    "  todos.setKey('items', (items) =>",
    "    items.map((t) => t.id === e.data.id ? { ...t, done: !t.done } : t)",
    "  );",
    "});",
    "",
    "todos.on('remove', (e) => {",
    "  todos.setKey('items', (items) => items.filter((t) => t.id !== e.data.id));",
    "});",
    "",
    "todos.select(",
    "  (s) => ({",
    "    total: s.items.length,",
    "    active: s.items.filter((i) => !i.done).length,",
    "    completed: s.items.filter((i) => i.done).length,",
    "  }),",
    "  (stats) => console.log('Stats:', stats)",
    ");",
    "",
    "todos.emit('add', { text: 'Learn ztore' });",
    "todos.emit('add', { text: 'Build something' });",
    "todos.emit('add', { text: 'Write docs' });",
    "todos.emit('toggle', { id: todos.get().items[0].id });",
    "console.log('All items:', todos.get().items);",
  ].join("\n"),

  auth: [
    "// ========================================",
    "// USER AUTH with events",
    "// ========================================",
    "const auth = createStore({",
    "  user: null, token: null, loading: false, error: null,",
    "});",
    "",
    "auth.on('login', async (e) => {",
    "  auth.setKey('loading', true);",
    "  auth.setKey('error', null);",
    "  await new Promise((r) => setTimeout(r, 300));",
    "  const user = { id: 1, name: e.data.username, role: 'admin' };",
    "  const token = 'tok_' + Math.random().toString(36).slice(2);",
    "  auth.setKey('user', user);",
    "  auth.setKey('token', token);",
    "  auth.setKey('loading', false);",
    "  auth.emit('login:success', { user });",
    "  console.log('Logged in as:', user.name);",
    "});",
    "",
    "auth.on('logout', () => {",
    "  auth.setKey('user', null);",
    "  auth.setKey('token', null);",
    "  console.log('Logged out');",
    "});",
    "",
    "auth.on('login:success', (e) => {",
    "  console.log('Welcome,', e.data.user.name);",
    "});",
    "",
    "auth.emit('login', { username: 'alice' });",
    "setTimeout(() => auth.emit('logout'), 800);",
  ].join("\n"),

  cart: [
    "// ========================================",
    "// SHOPPING CART",
    "// ========================================",
    "const cart = createStore({ items: [], coupon: null });",
    "",
    "const products = [",
    "  { id: 1, name: 'Widget', price: 9.99 },",
    "  { id: 2, name: 'Gadget', price: 24.99 },",
    "  { id: 3, name: 'Doohickey', price: 4.99 },",
    "];",
    "",
    "cart.on('add', (e) => {",
    "  cart.setKey('items', (items) => [...items, { ...e.data, qty: 1 }]);",
    "  console.log('Added:', e.data.name);",
    "});",
    "",
    "cart.on('remove', (e) => {",
    "  cart.setKey('items', (items) => items.filter((i) => i.id !== e.data.id));",
    "  console.log('Removed:', e.data.name);",
    "});",
    "",
    "cart.on('qty', (e) => {",
    "  cart.setKey('items', (items) =>",
    "    items.map((i) => i.id === e.data.id ? { ...i, qty: e.data.qty } : i)",
    "  );",
    "});",
    "",
    "cart.select(",
    "  (s) => {",
    "    const sub = s.items.reduce((sum, i) => sum + i.price * i.qty, 0);",
    "    const disc = s.coupon === 'SAVE10' ? sub * 0.1 : 0;",
    "    return { subtotal: +sub.toFixed(2), discount: +disc.toFixed(2), total: +(sub - disc).toFixed(2) };",
    "  },",
    "  (t) => console.log('Cart:', t)",
    ");",
    "",
    "cart.emit('add', products[0]);",
    "cart.emit('add', products[1]);",
    "cart.emit('qty', { id: 1, qty: 3 });",
    "cart.setKey('coupon', 'SAVE10');",
  ].join("\n"),

  game: [
    "// ========================================",
    "// GAME HEALTH & COMBAT",
    "// ========================================",
    "const player = createStore({",
    "  name: 'Hero', hp: 100, maxHp: 100, xp: 0, level: 1, status: 'alive',",
    "});",
    "",
    "const enemies = createStore({",
    "  list: [",
    "    { id: 'goblin', name: 'Goblin', hp: 30, atk: 8 },",
    "    { id: 'orc', name: 'Orc', hp: 60, atk: 12 },",
    "  ],",
    "});",
    "",
    "player.on('damage', (e) => {",
    "  player.setKey('hp', (hp) => Math.max(0, hp - e.data.amount));",
    "  const pct = Math.round(player.get().hp / player.get().maxHp * 100);",
    "  console.log(player.get().name + ' takes ' + e.data.amount + ' damage (' + pct + '% HP)');",
    "  if (player.get().hp <= 0) {",
    "    player.setKey('status', 'dead');",
    "    player.emit('death');",
    "  }",
    "});",
    "",
    "player.on('heal', (e) => {",
    "  const hp = Math.min(player.get().maxHp, player.get().hp + e.data.amount);",
    "  player.setKey('hp', hp);",
    "  console.log(player.get().name + ' heals ' + e.data.amount + ' HP');",
    "});",
    "",
    "player.on('xp_gain', (e) => {",
    "  const newXp = player.get().xp + e.data.amount;",
    "  const needed = player.get().level * 100;",
    "  if (newXp >= needed) {",
    "    player.setKey('level', (l) => l + 1);",
    "    player.setKey('xp', newXp - needed);",
    "    player.setKey('maxHp', (h) => h + 20);",
    "    player.setKey('hp', player.get().maxHp + 20);",
    "    console.log('LEVEL UP! Now level ' + player.get().level);",
    "  } else {",
    "    player.setKey('xp', newXp);",
    "  }",
    "});",
    "",
    "player.on('death', () => console.log('Game Over!'));",
    "",
    "const enemy = enemies.get().list[0];",
    "console.log('Fighting ' + enemy.name + '!');",
    "player.emit('damage', { amount: enemy.atk });",
    "player.emit('damage', { amount: enemy.atk });",
    "player.emit('heal', { amount: 15 });",
    "player.emit('damage', { amount: enemy.atk });",
    "player.emit('xp_gain', { amount: 120 });",
  ].join("\n"),

  chat: [
    "// ========================================",
    "// CHAT ROOM",
    "// ========================================",
    "const chat = createStore({",
    "  messages: [], users: {}, typing: null,",
    "});",
    "",
    "chat.on('join', (e) => {",
    "  chat.setKey('users', (u) => ({ ...u, [e.data.user]: { name: e.data.user, color: e.data.color } }));",
    "  chat.setKey('messages', (m) => [...m, { type: 'system', text: e.data.user + ' joined', ts: Date.now() }]);",
    "  console.log(e.data.user + ' joined the chat');",
    "});",
    "",
    "chat.on('message', (e) => {",
    "  const msg = { type: 'user', user: e.data.user, text: e.data.text, ts: Date.now() };",
    "  chat.setKey('messages', (m) => [...m, msg]);",
    "  console.log('[' + e.data.user + '] ' + e.data.text);",
    "});",
    "",
    "chat.on('leave', (e) => {",
    "  chat.setKey('users', (u) => { const n = {...u}; delete n[e.data.user]; return n; });",
    "  chat.setKey('messages', (m) => [...m, { type: 'system', text: e.data.user + ' left', ts: Date.now() }]);",
    "});",
    "",
    "chat.select((s) => s.messages.length, (count) => {",
    "  if (count > 0) document.title = '(' + count + ') Chat';",
    "});",
    "",
    "chat.emit('join', { user: 'Alice', color: '#58a6ff' });",
    "chat.emit('join', { user: 'Bob', color: '#3fb950' });",
    "chat.emit('message', { user: 'Alice', text: 'Hey Bob, have you used ztore?' });",
    "chat.emit('message', { user: 'Bob', text: 'Yeah! Only 138 lines!' });",
    "chat.emit('message', { user: 'Alice', text: 'Perfect for our project' });",
    "chat.emit('leave', { user: 'Bob' });",
  ].join("\n"),

  agent: [
    "// ========================================",
    "// AI AGENT with Tool Use",
    "// ========================================",
    "const agent = createStore({",
    "  status: 'idle',",
    "  messages: [],",
    "  pendingTool: null,",
    "  toolHistory: [],",
    "  memory: { known_facts: [] },",
    "});",
    "",
    "const tools = {",
    "  calculator(expr) {",
    "    if (!/^[\\d\\s+\\-*/().,]+$/.test(expr)) return 'Invalid expression';",
    "    return Function('\"use strict\"; return (' + expr + ')')();",
    "  },",
    "  search(query) {",
    "    const db = { 'weather in london': '15C, cloudy', 'capital of france': 'Paris', 'population': '8 billion' };",
    "    return db[query.toLowerCase()] || 'No results for: ' + query;",
    "  },",
    "  note(text) {",
    "    const fact = agent.get().memory;",
    "    fact.known_facts.push(text);",
    "    agent.setKey('memory', { ...fact });",
    "    return 'Noted: ' + text;",
    "  },",
    "};",
    "",
    "agent.on('think', (e) => {",
    "  agent.setKey('status', 'thinking');",
    "  const tc = e.data && e.data.tool;",
    "  if (tc) { agent.emit('execute', tc); return; }",
    "  const msg = (e.data && e.data.input) || 'Thinking...';",
    "  agent.setKey('messages', (m) => [...m, { role: 'assistant', content: msg }]);",
    "  agent.setKey('status', 'done');",
    "});",
    "",
    "agent.on('execute', (e) => {",
    "  const { name, args } = e.data;",
    "  agent.setKey('pendingTool', name);",
    "  agent.setKey('status', 'executing');",
    "  const tool = tools[name];",
    "  if (!tool) { agent.emit('error', { message: 'Unknown tool: ' + name }); return; }",
    "  const result = tool(args);",
    "  agent.setKey('toolHistory', (h) => [...h, { name, args, result, ts: Date.now() }]);",
    "  agent.setKey('pendingTool', null);",
    "  console.log('Tool:', name, '=>', result);",
    "  agent.emit('think', { input: 'Tool ' + name + ' returned: ' + JSON.stringify(result) });",
    "});",
    "",
    "console.log('=== Agent Session ===');",
    "agent.emit('think', { input: 'Calculate 45 * 32', tool: { name: 'calculator', args: '45 * 32' } });",
    "setTimeout(() => agent.emit('think', { input: 'Search London weather', tool: { name: 'search', args: 'weather in london' } }), 100);",
    "setTimeout(() => agent.emit('think', { input: 'Note the result', tool: { name: 'note', args: 'London weather is 15C' } }), 200);",
    "setTimeout(() => {",
    "  console.log('Memory:', agent.get().memory);",
    "  console.log('Tools used:', agent.get().toolHistory.length);",
    "}, 400);",
  ].join("\n"),

  form: [
    "// ========================================",
    "// FORM STATE with Validation",
    "// ========================================",
    "const form = createStore({",
    "  fields: {",
    "    name: { value: '', error: null, touched: false },",
    "    email: { value: '', error: null, touched: false },",
    "    age: { value: '', error: null, touched: false },",
    "  },",
    "  submitted: false,",
    "});",
    "",
    "function validate(field, value) {",
    "  if (field === 'name') return !value.trim() ? 'Required' : value.length < 2 ? 'Too short' : null;",
    "  if (field === 'email') return !value.includes('@') ? 'Invalid email' : null;",
    "  if (field === 'age') { const n = parseInt(value); return isNaN(n) ? 'Must be a number' : n < 18 ? 'Must be 18+' : null; }",
    "  return null;",
    "}",
    "",
    "form.on('change', (e) => {",
    "  const { field, value } = e.data;",
    "  const error = validate(field, value);",
    "  form.setKey('fields', (f) => ({",
    "    ...f,",
    "    [field]: { value, error, touched: true },",
    "  }));",
    "});",
    "",
    "form.on('submit', () => {",
    "  const fields = form.get().fields;",
    "  let hasError = false;",
    "  const next = {};",
    "  for (const k in fields) {",
    "    const err = validate(k, fields[k].value);",
    "    next[k] = { value: fields[k].value, error: err, touched: true };",
    "    if (err) hasError = true;",
    "  }",
    "  form.setKey('fields', next);",
    "  form.setKey('submitted', !hasError);",
    "  if (!hasError) {",
    "    const vals = {}; for (const k in next) vals[k] = next[k].value;",
    "    console.log('Submitted:', vals);",
    "  } else {",
    "    console.log('Form has errors');",
    "  }",
    "});",
    "",
    "form.emit('change', { field: 'name', value: 'Alice' });",
    "form.emit('change', { field: 'email', value: 'alice@' });",
    "form.emit('change', { field: 'age', value: '25' });",
    "form.emit('submit');",
    "form.emit('change', { field: 'email', value: 'alice@example.com' });",
    "form.emit('submit');",
  ].join("\n"),

  pubsub: [
    "// ========================================",
    "// PUB/SUB EVENT BUS",
    "// ========================================",
    "const bus = createStore({});",
    "",
    "bus.on('user:created', (e) => {",
    "  console.log('Analytics:', e.data);",
    "});",
    "",
    "bus.on('user:created', (e) => {",
    "  console.log('Welcome email to:', e.data.email);",
    "});",
    "",
    "bus.on('user:created', (e) => {",
    "  console.log('Provision storage for:', e.data.name);",
    "});",
    "",
    "bus.on('order:placed', (e) => {",
    "  console.log('Order:', e.data.id, 'Total:', e.data.total);",
    "  bus.emit('inventory:reserve', { items: e.data.items });",
    "});",
    "",
    "bus.once('inventory:reserve', (e) => {",
    "  console.log('Reserved', e.data.items.length, 'items');",
    "});",
    "",
    "bus.emit('user:created', { id: 1, name: 'Alice', email: 'alice@test.com' });",
    "bus.emit('order:placed', { id: 'ORD-001', items: ['widget','gadget'], total: 34.98 });",
  ].join("\n"),

  undo: [
    "// ========================================",
    "// UNDO / REDO",
    "// ========================================",
    "const doc = createStore({ text: '', cursor: 0 });",
    "const past = [], future = [];",
    "",
    "doc.subscribe((state, prev) => {",
    "  if (prev) { past.push(structuredClone(prev)); future.length = 0; }",
    "});",
    "",
    "doc.on('type', (e) => {",
    "  doc.setKey('text', (t) => t + e.data.char);",
    "  doc.setKey('cursor', (c) => c + 1);",
    "  console.log('Text:', JSON.stringify(doc.get().text));",
    "});",
    "",
    "doc.on('undo', () => {",
    "  if (!past.length) return console.log('Nothing to undo');",
    "  const prev = past.pop();",
    "  future.push(structuredClone(doc.get()));",
    "  doc.set(prev);",
    "  console.log('Undo ->', JSON.stringify(doc.get().text));",
    "});",
    "",
    "doc.on('redo', () => {",
    "  if (!future.length) return console.log('Nothing to redo');",
    "  const next = future.pop();",
    "  past.push(structuredClone(doc.get()));",
    "  doc.set(next);",
    "  console.log('Redo ->', JSON.stringify(doc.get().text));",
    "});",
    "",
    "doc.emit('type', { char: 'h' });",
    "doc.emit('type', { char: 'e' });",
    "doc.emit('type', { char: 'l' });",
    "doc.emit('type', { char: 'l' });",
    "doc.emit('type', { char: 'o' });",
    "doc.emit('undo'); doc.emit('undo');",
    "doc.emit('redo');",
    "doc.emit('type', { char: 'p' });",
    "doc.emit('type', { char: '!' });",
  ].join("\n"),

  pagination: [
    "// ========================================",
    "// PAGINATION / INFINITE SCROLL",
    "// ========================================",
    "const DB = Array.from({ length: 37 }, (_, i) => ({",
    "  id: i + 1, title: 'Item ' + (i + 1), value: Math.random() * 1000 | 0,",
    "}));",
    "",
    "const page = createStore({",
    "  data: [], page: 1, perPage: 5,",
    "  loading: false, hasMore: true, total: 0,",
    "});",
    "",
    "page.on('load', () => {",
    "  if (page.get().loading || !page.get().hasMore) return;",
    "  page.setKey('loading', true);",
    "  setTimeout(() => {",
    "    const p = page.get().page, per = page.get().perPage;",
    "    const items = DB.slice((p - 1) * per, p * per);",
    "    page.setKey('data', (d) => [...d, ...items]);",
    "    page.setKey('total', DB.length);",
    "    page.setKey('page', (n) => n + 1);",
    "    page.setKey('hasMore', p * per < DB.length);",
    "    page.setKey('loading', false);",
    "    console.log('Loaded page', p, '- total:', page.get().data.length, '/', DB.length);",
    "  }, 200);",
    "});",
    "",
    "page.emit('load');",
    "setTimeout(() => page.emit('load'), 250);",
    "setTimeout(() => page.emit('load'), 500);",
  ].join("\n"),

  "state-machine": [
    "// ========================================",
    "// STATE MACHINE (traffic light)",
    "// ========================================",
    "const traffic = createStore({",
    "  current: 'red', timer: 0, cycles: 0,",
    "});",
    "",
    "const config = {",
    "  red:    { duration: 6, next: 'green',  label: 'STOP' },",
    "  green:  { duration: 5, next: 'yellow', label: 'GO' },",
    "  yellow: { duration: 2, next: 'red',    label: 'CAUTION' },",
    "};",
    "",
    "traffic.on('tick', () => {",
    "  const s = traffic.get();",
    "  const cur = config[s.current];",
    "  const nt = s.timer + 1;",
    "  if (nt >= cur.duration) {",
    "    traffic.setKey('current', cur.next);",
    "    traffic.setKey('timer', 0);",
    "    traffic.setKey('cycles', (c) => c + 1);",
    "    console.log('Light:', config[traffic.get().current].label);",
    "  } else {",
    "    traffic.setKey('timer', nt);",
    "  }",
    "});",
    "",
    "traffic.on('emergency', () => {",
    "  traffic.setKey('current', 'green');",
    "  traffic.setKey('timer', 0);",
    "  console.log('EMERGENCY OVERRIDE: GREEN');",
    "});",
    "",
    "console.log('=== Traffic Light ===');",
    "for (let i = 0; i < 16; i++) traffic.emit('tick');",
    "console.log('Cycles:', traffic.get().cycles, '| State:', traffic.get().current);",
  ].join("\n"),
};
